"""
categoryhistory.py — One "on this day" fact for every calendar day (366 entries).

Facts are themed around Indian history, geography, and culture — matching the
Sigmionary game's question categories. Includes Feb 29 for leap years.

Usage:
    from utils.categoryhistory import get_history_fact
    fact = get_history_fact(month=4, day=26)
"""

from __future__ import annotations

# Keys are (month, day). All 366 days of the calendar are covered.
_FACTS: dict[tuple[int, int], str] = {

    # ── January ───────────────────────────────────────────────────────────────
    (1,  1): "On January 1, 1877, Queen Victoria was proclaimed Empress of India at the grand Imperial Assemblage in Delhi, formally uniting the subcontinent under British rule.",
    (1,  2): "On January 2, 1757, Robert Clive's forces recaptured Calcutta from Nawab Siraj ud-Daulah, a turning point that cemented British power over Bengal.",
    (1,  3): "On January 3, 1889, the Indian National Congress held its fifth session in Bombay, advancing demands for representative governance that would shape the independence movement.",
    (1,  4): "On January 4, 1948, Burma (now Myanmar) gained independence — just months after India — beginning Asia's great wave of decolonization.",
    (1,  5): "On January 5, 1592, Mughal Prince Salim — later Emperor Jahangir — was born; his reign elevated Mughal miniature painting to an unmatched artistic peak.",
    (1,  6): "On January 6, 1664, Shivaji Maharaj's forces raided the wealthy Mughal port of Surat, the first bold demonstration that Maratha power could challenge the empire.",
    (1,  7): "On January 7, 1761, the Third Battle of Panipat was fought, where Afghan forces defeated the Marathas in one of the largest and bloodiest battles of 18th-century India.",
    (1,  8): "On January 8, 1926, the first regular Indian broadcasting service began in Bombay, laying the foundation for All India Radio.",
    (1,  9): "On January 9, 1915, Mahatma Gandhi returned to India from South Africa, landing at Bombay Harbour to begin leading the mass non-violent freedom struggle.",
    (1, 10): "On January 10, 1966, Lal Bahadur Shastri died in Tashkent — a day after signing a peace deal with Pakistan — making him the only Indian Prime Minister to die abroad while in office.",
    (1, 11): "On January 11, 1784, Sir William Jones founded the Asiatic Society of Bengal in Calcutta, pioneering the scholarly study of Indian languages, history, and sacred texts.",
    (1, 12): "On January 12, 1863, Swami Vivekananda was born in Calcutta; he later electrified the 1893 Chicago Parliament of Religions by introducing Indian philosophy to the Western world.",
    (1, 13): "On January 13, 1949, a UN-brokered ceasefire ended the first Indo-Pakistani War over Kashmir, drawing boundaries that influence the two nations to this day.",
    (1, 14): "On January 14, Kerala and Tamil Nadu celebrate Makar Vilakku and Pongal respectively — among India's most dazzling harvest festivals, with millions lighting lamps at Sabarimala.",
    (1, 15): "On January 15, 1934, a devastating earthquake struck Bihar killing thousands; Mahatma Gandhi controversially called it 'divine punishment' for the sin of untouchability.",
    (1, 16): "On January 16, 1966, Indira Gandhi was elected India's first female Prime Minister by the Congress party, beginning one of the most consequential tenures in Indian political history.",
    (1, 17): "On January 17, 1781, Hyder Ali's son Tipu Sultan won the Battle of Pollilur against British forces — one of the most decisive early victories of the Anglo-Mysore Wars.",
    (1, 18): "On January 18, 1975, Arunachal Pradesh was given its current name as a Union Territory of India, recognising the distinct identity of India's diverse northeast.",
    (1, 19): "On January 19, 1966, Indira Gandhi was sworn in as Prime Minister — the first woman to hold India's highest executive office, and only the second woman to lead any republic globally.",
    (1, 20): "On January 20, 1990, India's President Venkataraman declared President's Rule in Jammu & Kashmir amid rising militancy, a pivotal moment in the state's modern history.",
    (1, 21): "On January 21, 1972, Manipur, Meghalaya, and Tripura were granted full statehood — expanding India's northeast with three distinct cultural and geographical identities.",
    (1, 22): "On January 22, 2024, Ram Mandir in Ayodhya was consecrated — marking the completion of a temple at one of Hinduism's most sacred sites after decades of legal and historical debate.",
    (1, 23): "On January 23, 1897, Netaji Subhas Chandra Bose was born in Cuttack; he would later form the Indian National Army and declare war on British India from Southeast Asia.",
    (1, 24): "On January 24, 1950, the Indian Constituent Assembly adopted 'Jana Gana Mana' — originally composed by Rabindranath Tagore — as India's national anthem.",
    (1, 25): "On January 25, 1971, Himachal Pradesh became the 18th state of India, carving out the Himalayan region into a full state from its former Union Territory status.",
    (1, 26): "On January 26, 1950, India's Constitution came into force and the nation officially became a Republic — a date now celebrated with grand parades on Rajpath in New Delhi.",
    (1, 27): "On January 27, 1901, Victoria, Queen of England and Empress of India, died at age 81, ending the longest reign in British history and a defining era of Indian colonial history.",
    (1, 28): "On January 28, 1986, the Space Shuttle Challenger disaster shocked the world; India's own space programme, begun humbly in 1962 with a rocket launched from Kerala's Thumba, had been quietly advancing since.",
    (1, 29): "On January 29, 1780, Hicky's Bengal Gazette — India's first English-language newspaper — was published in Calcutta, launching a free press that would become a tool of resistance.",
    (1, 30): "On January 30, 1948, Mahatma Gandhi was assassinated in New Delhi by Nathuram Godse, ending the life of the man who led India to independence through peaceful resistance.",
    (1, 31): "On January 31, 1929, the Indian National Congress raised the Tricolour on the banks of the Ravi river in Lahore, declaring Purna Swaraj — complete independence — as its goal.",

    # ── February ──────────────────────────────────────────────────────────────
    (2,  1): "On February 1, 1992, the Narasimha Rao government launched landmark economic liberalisation, opening India to foreign investment and reshaping its financial future.",
    (2,  2): "On February 2, 1835, Thomas Macaulay's famous Minute on Indian Education was submitted, proposing English as the medium of instruction in Indian schools — reshaping education for generations.",
    (2,  3): "On February 3, 1919, the Rowlatt Act was passed in the Imperial Legislative Council, triggering the nationwide protests that led directly to the Jallianwala Bagh massacre.",
    (2,  4): "On February 4, 1948, Ceylon (Sri Lanka) gained independence from Britain — the island neighbour of India's southern coast celebrated its first Republic Day 24 years later.",
    (2,  5): "On February 5, 1922, Gandhi called off the Non-Cooperation Movement after protestors killed 22 policemen at Chauri Chaura — demonstrating his absolute commitment to non-violence.",
    (2,  6): "On February 6, 1556, the 13-year-old Akbar became Mughal Emperor at Kalanaur, beginning a reign that would expand the empire to its greatest extent and champion religious pluralism.",
    (2,  7): "On February 7, 1948, the Indian Constituent Assembly debated the fundamental rights clauses, framing the legal foundation of the world's largest democracy.",
    (2,  8): "On February 8, 1876, the Famine Commission was established in British India, exposing how colonial policies caused — rather than merely failed to prevent — catastrophic famines.",
    (2,  9): "On February 9, 1931, Bhagat Singh, Sukhdev, and Rajguru were sentenced to death for the murder of British police officer J.P. Saunders — a verdict that sparked nationwide protests.",
    (2, 10): "On February 10, 1948, the Indian Constitution's Preamble was debated in the Constituent Assembly, with 'We the People of India' echoing the democratic aspirations of 400 million citizens.",
    (2, 11): "On February 11, 1942, Gandhi proposed his 'Quit India' resolution to the Congress Working Committee, setting the stage for the most decisive phase of the independence struggle.",
    (2, 12): "On February 12, 1948, M.S. Subbulakshmi performed at the United Nations in New York — the first Indian classical musician to receive that honour, representing the soul of Carnatic music.",
    (2, 13): "On February 13, 1931, the city of New Delhi was inaugurated as the capital of British India by the Viceroy Lord Irwin, built on a grand scale designed by Edwin Lutyens and Herbert Baker.",
    (2, 14): "On February 14, 2019, a devastating suicide bombing in Pulwama, Kashmir, killed 40 CRPF personnel — triggering a major escalation in India-Pakistan tensions.",
    (2, 15): "On February 15, 1564, Galileo Galilei was born — the same year that Emperor Akbar consolidated power over India; both figures changed how humanity understood the world.",
    (2, 16): "On February 16, 1948, the Indian Air Force conducted its first major post-independence operations over Kashmir, defending the newly acceded state from Pakistani tribal militias.",
    (2, 17): "On February 17, 1960, the Nagarjunasagar Dam project on the Krishna River was inaugurated by PM Nehru — one of the world's largest irrigation projects, transforming Andhra Pradesh.",
    (2, 18): "On February 18, 1930, Mahatma Gandhi announced the Salt March from Sabarmati Ashram — a 240-mile walk to the sea that became the most iconic act of civil disobedience in history.",
    (2, 19): "On February 19, 1630, Chhatrapati Shivaji Maharaj was born in the hill-fort of Shivneri, near Pune — the founder of the Maratha Empire, whose legacy shaped western India forever.",
    (2, 20): "On February 20, 1947, British Prime Minister Attlee announced Britain's plan to transfer power to India — setting June 1948 as the original deadline for independence.",
    (2, 21): "On February 21, 1952, Pakistan's Language Movement protests in East Pakistan claimed lives of students defending Bangla — events that ultimately led to the creation of Bangladesh in 1971.",
    (2, 22): "On February 22, 1978, India's first satellite Aryabhata — launched by the Soviets in 1975 — re-entered Earth's atmosphere after completing its mission, marking India's early space ambitions.",
    (2, 23): "On February 23, 1946, the Royal Indian Navy Mutiny broke out in Bombay, when Indian sailors revolted against British officers — a pivotal moment that accelerated independence.",
    (2, 24): "On February 24, 1739, Persian conqueror Nadir Shah defeated the Mughal forces at the Battle of Karnal, opening the road to Delhi and the looting of the Peacock Throne.",
    (2, 25): "On February 25, 1947, the British Cabinet Mission arrived in India to discuss the transfer of power — meetings that produced the blueprint for Indian independence and partition.",
    (2, 26): "On February 26, 1530, Babur died in Agra, ending the reign of the founder of the Mughal dynasty whose descendants would rule India for over 300 years.",
    (2, 27): "On February 27, 2002, communal violence in Godhra, Gujarat, killed 59 passengers on the Sabarmati Express — sparking riots that scarred the state and reverberated across Indian politics.",
    (2, 28): "On February 28, 1928, the Simon Commission arrived in India to review the Government of India Act 1919, triggering mass protests with the slogan 'Simon Go Back.'",
    (2, 29): "February 29 is a leap day that occurs once every four years — in Indian tradition, rare events like this are considered auspicious; the Sabarimala pilgrimage season also marks unique astronomical alignments in such years.",

    # ── March ─────────────────────────────────────────────────────────────────
    (3,  1): "On March 1, 1872, India's first population census was conducted under British rule, counting roughly 255 million people — a tradition that continues to this day.",
    (3,  2): "On March 2, 1931, Bhagat Singh, Sukhdev, and Rajguru were hanged at Lahore Central Jail — their martyrdom at age 23 turned them into icons of the Indian independence movement.",
    (3,  3): "On March 3, 1947, Punjab was partitioned on paper by the British — a prelude to one of the largest and most traumatic mass migrations in human history.",
    (3,  4): "On March 4, 1919, the first Jallianwala Bagh memorial committee was formed; the massacre that followed in April changed the course of the Indian independence movement forever.",
    (3,  5): "On March 5, 1946, Clement Attlee's government announced that India would receive dominion status — a historic step toward the independence that came 17 months later.",
    (3,  6): "On March 6, 1930, Mahatma Gandhi set out on the Dandi Salt March from Sabarmati Ashram with 78 followers, walking 241 miles to the Arabian Sea to make salt in defiance of British law.",
    (3,  7): "On March 7, 1971, Sheikh Mujibur Rahman delivered his historic speech in Dhaka calling for independence — a moment that set East Pakistan on the path to becoming Bangladesh.",
    (3,  8): "On March 8, International Women's Day, India honours pioneers like Savitribai Phule who opened the first school for girls in Pune in 1848, defying caste and gender norms.",
    (3,  9): "On March 9, 1757, Robert Clive defeated the Nawab of Bengal's forces at Chandannagar, tightening British control over eastern India's most prosperous region.",
    (3, 10): "On March 10, 1922, Gandhi was arrested for 'seditious writing' in Young India — he called it 'the proudest day of his life,' and accepted the sentence with characteristic dignity.",
    (3, 11): "On March 11, 1948, Nehru wrote his famous 'Tryst with Destiny' address — but it was originally delivered at midnight on August 15, 1947, greeting India's independence.",
    (3, 12): "On March 12, 1930, Mahatma Gandhi began the famous Salt March to Dandi — an act of civil disobedience that inspired freedom movements across the colonised world.",
    (3, 13): "On March 13, 1940, Udham Singh shot Michael O'Dwyer in London to avenge the Jallianwala Bagh massacre of 1919 — a radical act of justice that divided Indian opinion.",
    (3, 14): "On March 14, 1883, Karl Marx died in London — but his ideas profoundly influenced Indian labour movements and shaped the policies of post-independence Indian planning.",
    (3, 15): "On March 15, 1956, the States Reorganisation Act took effect, redrawing India's internal boundaries along linguistic lines — creating Kerala, among other new states.",
    (3, 16): "On March 16, 1976, India's first satellite launch vehicle (SLV) project was formally approved, setting ISRO on the path to its remarkable space programme.",
    (3, 17): "On March 17, 1527, Babur defeated Rana Sanga at the Battle of Khanwa, cementing Mughal supremacy over the Rajput kingdoms of northern India.",
    (3, 18): "On March 18, 1940, the Muslim League passed the Lahore Resolution — popularly called the 'Pakistan Resolution' — laying the groundwork for Partition and Pakistan's creation.",
    (3, 19): "On March 19, 1947, Lord Mountbatten arrived in India as the last Viceroy, with a mandate to hand over power — a process that culminated in August with independence and Partition.",
    (3, 20): "On March 20, 1602, the Dutch East India Company was founded — a rival to the English East India Company that would compete for trade dominance across the Indian Ocean.",
    (3, 21): "On March 21 (Spring Equinox), Navroz — the Persian New Year celebrated by India's Parsi community — marks new beginnings with prayers, feasts, and centuries of Zoroastrian tradition.",
    (3, 22): "On March 22, 1993, Bombay was hit by a series of bombings killing over 250 people — the most deadly terrorist attack on Indian soil at the time, which reshaped urban security policy.",
    (3, 23): "On March 23, 1931, Bhagat Singh was hanged in Lahore; he was 23 years old and had refused a pardon, saying a revolutionary's death was the most powerful argument for independence.",
    (3, 24): "On March 24, 1942, the Cripps Mission arrived in India proposing dominion status after the war — Gandhi famously called it 'a post-dated cheque on a crashing bank.'",
    (3, 25): "On March 25, 1971, Pakistani military launched Operation Searchlight in East Pakistan — the brutal crackdown that began the Bangladesh Liberation War and sent 10 million refugees into India.",
    (3, 26): "On March 26, 1971, Bangladesh declared independence from Pakistan — a declaration supported militarily by India, which deployed troops in December to decisively end the conflict.",
    (3, 27): "On March 27, 1668, the British Crown transferred Bombay to the East India Company for a rent of £10 a year — and so began the city's transformation into India's greatest commercial hub.",
    (3, 28): "On March 28, 1930, Gandhi's Salt March reached halfway to Dandi; foreign journalists covering the trek sent dispatches that turned world attention to India's independence movement.",
    (3, 29): "On March 29, 1857, sepoy Mangal Pandey fired the first shots of the Indian Revolt at Barrackpore — the event that triggered the 1857 uprising against the British East India Company.",
    (3, 30): "On March 30, 1949, Rajasthan was formed by integrating 22 princely states — its name meaning 'Land of Kings,' and home to the Thar Desert, Jaisalmer, and the Aravalli Range.",
    (3, 31): "On March 31, 1774, Warren Hastings became the first Governor-General of Bengal, establishing the administrative machinery that would eventually govern all of British India.",

    # ── April ─────────────────────────────────────────────────────────────────
    (4,  1): "On April 1, 1869, the Suez Canal opened to traffic — drastically cutting the sea route between Europe and India from 24,000 km (around Africa) to just 11,000 km.",
    (4,  2): "On April 2, 1983, India won the Cricket World Cup in London under Kapil Dev's captaincy — a victory so unexpected it was described as India's greatest sporting miracle.",
    (4,  3): "On April 3, 1680, Chhatrapati Shivaji Maharaj died at Raigad Fort — leaving behind a Maratha kingdom that would outlast even the Mughal Empire in many regions of India.",
    (4,  4): "On April 4, 1905, Lord Curzon's partition of Bengal came into effect, triggering a nationwide Swadeshi movement — the first mass economic boycott against British goods.",
    (4,  5): "On April 5, 1930, Gandhi reached Dandi and made salt from the sea — a simple act that broke British law and galvanised millions across India and the world.",
    (4,  6): "On April 6, 1930, thousands of Indians across the country violated the Salt Laws in solidarity with Gandhi, launching one of the most successful civil disobedience campaigns in history.",
    (4,  7): "On April 7, 1875, the Arya Samaj was founded by Dayananda Saraswati in Bombay, advocating for Hindu reform, women's education, and rejection of caste discrimination.",
    (4,  8): "On April 8, 1929, Bhagat Singh and Batukeshwar Dutt threw non-lethal bombs in the Central Legislative Assembly in Delhi — their slogan 'Inquilab Zindabad' echoed across India.",
    (4,  9): "On April 9, 1669, Emperor Aurangzeb ordered the demolition of Hindu temples across the Mughal empire — a policy that deepened religious divisions still felt centuries later.",
    (4, 10): "On April 10, 1930, over 2,500 Congress volunteers seized the Dharasana salt works in Gujarat — and were beaten without resistance, watched by American journalist Webb Miller whose dispatch shocked the world.",
    (4, 11): "On April 11, 1951, India held its first general election under universal adult franchise — the largest democratic exercise in history at the time, with 176 million eligible voters.",
    (4, 12): "On April 12, 1944, the Indian National Army crossed into Manipur from Burma in its march toward Delhi — the advance that got within sight of Indian soil before being turned back.",
    (4, 13): "On April 13, 1919, British troops under General Dyer fired on unarmed civilians gathered at Jallianwala Bagh in Amritsar — killing hundreds in the most notorious act of colonial brutality in India.",
    (4, 14): "On April 14, 1891, B.R. Ambedkar — the architect of India's Constitution, champion of Dalit rights, and towering intellectual — was born in Mhow, Central India.",
    (4, 15): "On April 15, 1469, Guru Nanak Dev Ji, the founder of Sikhism, was born in Talwandi (now Nankana Sahib, Pakistan) — his teachings of equality and devotion shaped a global religion.",
    (4, 16): "On April 16, 1853, India's first passenger railway ran from Bombay to Thane, covering 34 km in 75 minutes — launching a railway network that would become the world's fourth largest.",
    (4, 17): "On April 17, 1972, the Indian Cricket team defeated England in a Test match for the first time in England — a landmark achievement under the captaincy of Ajit Wadekar.",
    (4, 18): "On April 18, 1930, Indian revolutionary Surya Sen led the Chittagong Armoury Raid, temporarily seizing British weaponry — inspiring the 1971 Bangladesh freedom struggle decades later.",
    (4, 19): "On April 19, 1975, India launched its first satellite, Aryabhata, from a Soviet rocket station — named after the 5th-century Indian astronomer who calculated pi and the Earth's rotation.",
    (4, 20): "On April 20, 2001, Kerala's famous Thrissur Pooram festival was held — a 200-year-old tradition of 15 competing elephant processions and thunderous percussion orchestras drawing millions.",
    (4, 21): "On April 21, 1526, Babur defeated Ibrahim Lodi at the First Battle of Panipat using firearms for the first time in India — founding the Mughal dynasty that shaped the subcontinent for 300 years.",
    (4, 22): "On April 22, 1500, Portuguese explorer Pedro Álvares Cabral made first European contact with Brazil — the same decade Vasco da Gama had opened the sea route to India that changed world history.",
    (4, 23): "On April 23, 1564, William Shakespeare was born — the same year Emperor Akbar's court was already producing its own literary renaissance, with poetry and histories in Persian, Hindi, and Sanskrit.",
    (4, 24): "On April 24, 1993, India ratified the Biological Diversity Convention — committing to protect its exceptional biodiversity including the Western Ghats, one of the world's eight 'hottest hotspots.'",
    (4, 25): "On April 25, 1960, the Indus Waters Treaty was signed between India and Pakistan, allocating river waters that sustain hundreds of millions of farmers across both nations.",
    (4, 26): "On April 26, 1987, Kerala's Guruvayur temple elephant Guruvayur Keshavan died at an estimated 72 years — the most beloved temple elephant in India, whose tusks are preserved in the temple to this day.",
    (4, 27): "On April 27, 1961, Goa, Daman, and Diu were liberated from Portuguese rule by Indian military action — ending over 450 years of Portuguese presence on the Indian subcontinent.",
    (4, 28): "On April 28, 1947, Nehru signed the Indian Independence Act in London — an agreement that set August 15 as India's independence date and created the framework for the transfer of power.",
    (4, 29): "On April 29, 1639, the foundation stone of Fort St. George — which would grow into Madras (now Chennai) — was laid by the British East India Company, marking the birth of one of India's great cities.",
    (4, 30): "On April 30, 1006 CE, a supernova now called SN 1006 blazed across the night sky; Indian astronomers of the Chola period are believed to have recorded this rare stellar event.",

    # ── May ───────────────────────────────────────────────────────────────────
    (5,  1): "On May 1, 1960, the State of Maharashtra was formed after the Samyukta Maharashtra movement — the same day Goa, Daman & Diu was still under Portuguese rule, just 21 km from the new state.",
    (5,  2): "On May 2, 1519, Leonardo da Vinci died in France — the same year that the Vijayanagara Empire at its peak in southern India was patronising some of the most exquisite Dravidian temple architecture.",
    (5,  3): "On May 3, 1765, the British East India Company was granted the Diwani (revenue collection rights) over Bengal — the decisive moment India's wealth began flowing to Britain.",
    (5,  4): "On May 4, 1799, Tipu Sultan was killed at the fall of Seringapatam — the end of Mysore's fierce resistance and the last major opposition to British supremacy in South India.",
    (5,  5): "On May 5, 1961, astronaut Alan Shepard became the first American in space; two months later, India's own space programme was formally established with INCOSPAR under Vikram Sarabhai.",
    (5,  6): "On May 6, 1954, the Panchsheel Agreement was signed between India and China, enshrining five principles of peaceful coexistence — trust that shattered in the 1962 border war.",
    (5,  7): "On May 7, 1861, Rabindranath Tagore was born in Calcutta; he became the first Asian Nobel laureate in Literature (1913), and wrote the national anthems of both India and Bangladesh.",
    (5,  8): "On May 8, 1933, Mahatma Gandhi began a 21-day fast in Poona Jail to protest the British government's communal award — his capacity for principled self-sacrifice was unmatched.",
    (5,  9): "On May 9, 1942, Gandhi called for British withdrawal from India — the 'Quit India' movement declared three months later became the largest popular uprising in Indian history.",
    (5, 10): "On May 10, 1857, the Indian Revolt broke out at Meerut when sepoys rebelled against British rule — the uprising that would eventually force Britain to abolish the East India Company entirely.",
    (5, 11): "On May 11, 1998, India conducted the Pokhran-II nuclear tests under Operation Shakti — declaring itself a nuclear-armed state and triggering global sanctions against the country.",
    (5, 12): "On May 12, 1949, Hyderabad's accession to India was completed, ending the rule of the Nizam — one of the world's wealthiest rulers — and integrating the city into the Indian union.",
    (5, 13): "On May 13, 1952, India's first general election concluded with the Indian National Congress winning 364 of 489 seats — a landslide that set India on its democratic course.",
    (5, 14): "On May 14, 1948, Israel declared independence — the same week India's Constituent Assembly was debating fundamental rights, both nations building democracy on the ruins of British colonial power.",
    (5, 15): "On May 15, 1951, the Indian Planning Commission released the First Five-Year Plan, modelling India's economic development after Soviet planning but adapted to a democratic framework.",
    (5, 16): "On May 16, 1975, Sikkim officially became the 22nd state of India, ending its status as a protectorate — completing the integration of the final Himalayan monarchy into the Indian union.",
    (5, 17): "On May 17, 1540, Sher Shah Suri defeated Humayun at the Battle of Kanauj, temporarily ousting the Mughals — Sher Shah then built the Grand Trunk Road that still connects Pakistan to Bangladesh.",
    (5, 18): "On May 18, 1974, India detonated its first nuclear device near Pokhran in Rajasthan — called 'Smiling Buddha,' it made India the world's sixth nuclear power and shocked Western governments.",
    (5, 19): "On May 19, 1994, Sushmita Sen of India was crowned Miss Universe — the first Indian woman to win the title, a milestone that opened new cultural conversations about Indian identity.",
    (5, 20): "On May 20, 1498, Vasco da Gama landed at Kozhikode (Calicut) in Kerala — the first European to reach India by sea, opening a trade route that would transform world history.",
    (5, 21): "On May 21, 1991, Rajiv Gandhi was assassinated near Chennai by an LTTE suicide bomber — the targeted killing of India's youngest Prime Minister shocked the nation and the world.",
    (5, 22): "On May 22, 1773, the Regulating Act was passed by Britain, imposing direct parliamentary oversight on the East India Company's activities in India for the first time.",
    (5, 23): "On May 23, 2019, the BJP won India's general election with 303 seats, giving Narendra Modi a second term as Prime Minister with the strongest mandate since Rajiv Gandhi in 1984.",
    (5, 24): "On May 24, 1543, Copernicus published his heliocentric model of the solar system — centuries before, Indian mathematician Aryabhata had already argued the Earth rotates on its own axis.",
    (5, 25): "On May 25, 1970, Doordarshan — India's public television broadcaster — began experimental transmissions in Bombay, bringing moving images to a nation that had only had radio since 1927.",
    (5, 26): "On May 26, 2014, Narendra Modi was sworn in as India's 14th Prime Minister — inaugurating a new era with the largest gathering of foreign leaders at an Indian swearing-in ceremony.",
    (5, 27): "On May 27, 1964, Prime Minister Jawaharlal Nehru died in New Delhi — the architect of modern India who had steered the nation through its first 17 years of independence.",
    (5, 28): "On May 28, 1998, Pakistan responded to India's Pokhran tests with its own nuclear tests, triggering global alarm and cementing the subcontinent as a nuclear-armed zone.",
    (5, 29): "On May 29, 1953, Tenzing Norgay and Edmund Hillary became the first climbers to summit Mount Everest — Tenzing, an Indian Nepali Sherpa, became a hero across South Asia.",
    (5, 30): "On May 30, 1431, Joan of Arc was burned at the stake in France — the same century that the Vijayanagara Empire was building Hampi's magnificent temples on the Tungabhadra River.",
    (5, 31): "On May 31, 1910, the Union of South Africa was formed — a milestone that inspired Mahatma Gandhi, who had fought apartheid in South Africa since 1893, to intensify his civil rights campaigns.",

    # ── June ──────────────────────────────────────────────────────────────────
    (6,  1): "On June 1, 1926, Marilyn Monroe was born — but more significantly for India, June 1956 saw the States Reorganisation Act reshape India's map along linguistic lines, creating Kerala.",
    (6,  2): "On June 2, 1858, the East India Company's rule formally ended as the British Crown assumed direct governance of India — a change triggered by the 1857 uprising.",
    (6,  3): "On June 3, 1947, Lord Mountbatten announced the Partition Plan, setting in motion the events that would create India and Pakistan by August 15 — alongside the largest human migration in history.",
    (6,  4): "On June 4, 1989, the Tiananmen Square crackdown happened in China; across the border, India's democracy was holding its ninth general election in a free and fair process.",
    (6,  5): "On June 5, World Environment Day, India's biodiversity hotspots — from the Andaman Islands to the Western Ghats — are globally celebrated as irreplaceable natural treasures.",
    (6,  6): "On June 6, 1984, Operation Blue Star was launched — the Indian Army's controversial storming of the Golden Temple in Amritsar to flush out militants sheltering inside the Sikh holy site.",
    (6,  7): "On June 7, 1893, Mahatma Gandhi was thrown off a train at Pietermaritzburg, South Africa, for refusing to move to a 'coloured' coach — the moment he resolved to fight racial injustice.",
    (6,  8): "On June 8, 1965, the Indian rupee was officially devalued for the first time post-independence — a reflection of the economic pressures following the 1962 war with China.",
    (6,  9): "On June 9, 1931, the Indian National Congress Working Committee met in Allahabad to review the Gandhi-Irwin Pact — a short-lived truce that suspended the civil disobedience movement.",
    (6, 10): "On June 10, 1964, Lal Bahadur Shastri was appointed India's second Prime Minister, known for his simple lifestyle, the 'Jai Jawan Jai Kisan' slogan, and decisive leadership in the 1965 war.",
    (6, 11): "On June 11, 1942, the British government proposed autonomy for India after World War II in exchange for wartime cooperation — Gandhi rejected it as 'a post-dated cheque on a failing bank.'",
    (6, 12): "On June 12, 1975, the Allahabad High Court found Indira Gandhi guilty of electoral malpractice — a verdict that she responded to by declaring the Emergency the following day.",
    (6, 13): "On June 13, 2013, a massive flash flood devastated the Kedarnath temple in Uttarakhand, killing thousands of pilgrims — a tragedy that highlighted the vulnerability of India's Himalayan pilgrimage routes.",
    (6, 14): "On June 14, 1947, a Punjab Boundary Commission was established to draw the borders that would divide the region between India and Pakistan — a task completed in just five weeks.",
    (6, 15): "On June 15, 2015, India and Bangladesh finalised a historic land boundary agreement, peacefully resolving 68 years of disputes over 162 enclaves — a rare model of diplomatic resolution.",
    (6, 16): "On June 16, 1946, the Cabinet Mission Plan was published, proposing a united India under a federal structure — rejected by both Congress and the Muslim League, making Partition inevitable.",
    (6, 17): "On June 17, 1631, Mumtaz Mahal died in childbirth in Burhanpur; her grieving husband Shah Jahan began planning the Taj Mahal — arguably the world's greatest monument to love.",
    (6, 18): "On June 18, 1858, Rani Lakshmibai of Jhansi died fighting British forces near Gwalior — she became the most enduring symbol of female courage in India's freedom struggle.",
    (6, 19): "On June 19, 1947, Nehru announced that a commission would determine the future of princely states — a process that integrated 565 kingdoms into the Indian union within three years.",
    (6, 20): "On June 20, 1756, the 'Black Hole of Calcutta' incident occurred when Nawab Siraj ud-Daulah imprisoned British soldiers in a tiny cell, causing many deaths — a story later weaponised by British propaganda.",
    (6, 21): "On June 21, 2015, the United Nations observed the first International Yoga Day — a global initiative proposed by India's PM Modi that united 192 nations through India's ancient practice.",
    (6, 22): "On June 22, 1897, Bal Gangadhar Tilak was arrested for sedition after a militant attack on British officers — his trial made him 'Lokmanya' (respected by the people) across India.",
    (6, 23): "On June 23, 1757, the Battle of Plassey was fought — Robert Clive's victory over Nawab Siraj ud-Daulah using treachery secured British dominance over Bengal and transformed India's history.",
    (6, 24): "On June 24, 1948, the Constituent Assembly of India debated the Directive Principles of State Policy — guidelines for governance that have shaped Indian welfare legislation for 75 years.",
    (6, 25): "On June 25, 1975, India's President declared a state of Emergency at PM Indira Gandhi's request — suspending civil liberties and elections for 21 months in the darkest chapter of Indian democracy.",
    (6, 26): "On June 26, 1975, all opposition leaders were arrested in the first hours of the Emergency — Jayaprakash Narayan's detention became the symbol of democracy's most serious test in India.",
    (6, 27): "On June 27, 1946, Sardar Vallabhbhai Patel was elected Deputy Prime Minister — the 'Iron Man of India' who would go on to integrate 565 princely states into the Indian union.",
    (6, 28): "On June 28, 1838, Queen Victoria was crowned at Westminster Abbey — less than 40 years before she would be crowned Empress of India, connecting Britain's monarchy to its Indian empire.",
    (6, 29): "On June 29, 1613, the British East India Company established its first trading post in Surat, Gujarat — the foothold that would grow over 200 years into control of the entire Indian subcontinent.",
    (6, 30): "On June 30, 1947, the Radcliffe Commission began drawing lines that would divide Punjab and Bengal — Cyril Radcliffe had never visited India and completed the partition map in just five weeks.",

    # ── July ──────────────────────────────────────────────────────────────────
    (7,  1): "On July 1, 1862, the Archaeological Survey of India was established under Alexander Cunningham — the body that would go on to protect and excavate thousands of India's ancient sites.",
    (7,  2): "On July 2, 1505, the second Portuguese Viceroy Francisco de Almeida arrived in India, establishing a chain of fortified ports from Kozhikode to Goa that controlled the Indian Ocean trade.",
    (7,  3): "On July 3, 1866, the Bhils of central India launched an armed revolt against British forest policies — one of the many tribal uprisings that preceded India's formal independence movement.",
    (7,  4): "On July 4, 1776, the United States declared independence — an event studied closely by Indian nationalists who would invoke the same Enlightenment principles in their own struggle 170 years later.",
    (7,  5): "On July 5, 1830, Charles Metcalfe proposed freedom of the Indian press — a revolutionary idea for the time that influenced the development of India's vibrant newspaper culture.",
    (7,  6): "On July 6, 1944, Mahatma Gandhi addressed Hitler in a letter as 'Dear Friend,' appealing to his humanity — a diplomatic gesture as audacious as it was futile.",
    (7,  7): "On July 7, 1822, the first steam-powered vessel sailed in Indian waters on the Hooghly River near Calcutta — a technical revolution that would transform Indian trade and travel.",
    (7,  8): "On July 8, 1497, Vasco da Gama set sail from Lisbon on the voyage that would lead him to Calicut, Kerala — opening a sea route that ended the Arab monopoly on the Indian spice trade.",
    (7,  9): "On July 9, 1875, the Indian Public Works Department completed the first major section of the Ganges Canal — an engineering marvel that brought irrigation to millions across the Doab plains.",
    (7, 10): "On July 10, 1806, the Vellore Mutiny broke out when Indian sepoys revolted against new dress regulations seen as an attack on their religious identity — a precursor to the 1857 uprising.",
    (7, 11): "On July 11, 2006, serial bombings on Mumbai's suburban trains killed 209 people — an attack on the city's famous 'lifeline,' the daily reality for millions of ordinary Mumbaikars.",
    (7, 12): "On July 12, 2001, the Agra Summit between PM Vajpayee and President Musharraf failed to resolve the Kashmir dispute — a meeting that raised and then dashed hopes for South Asian peace.",
    (7, 13): "On July 13, 1943, the Quit India underground movement in Satara district established a 'parallel government' — one of the most remarkable acts of democratic defiance under colonial rule.",
    (7, 14): "On July 14, 1789, the Bastille fell in Paris; Indian revolutionaries including Bipin Chandra Pal studied the French Revolution as a model for overthrowing colonial power.",
    (7, 15): "On July 15, 1999, Indian forces secured the peaks of Kargil, completing Operation Vijay after 11 weeks of high-altitude fighting — reclaiming territory occupied by Pakistani forces.",
    (7, 16): "On July 16, 1945, the world's first nuclear bomb was tested at Trinity, New Mexico; India would conduct its own test 29 years later, naming it 'Smiling Buddha.'",
    (7, 17): "On July 17, 1794, revolutionary leader Maximilien Robespierre was arrested in France — the same year that British forces consolidated control over Mysore following Tipu Sultan's defeat.",
    (7, 18): "On July 18, 1918, Nelson Mandela was born in South Africa; Gandhi, who had transformed political life in South Africa two decades earlier, deeply influenced Mandela's non-violent resistance.",
    (7, 19): "On July 19, 1947, India's last cricket match under the British Raj was played — just 27 days before independence — an oddly peaceful moment amid the turbulence of Partition.",
    (7, 20): "On July 20, 1969, humans first landed on the Moon; India's own lunar programme would culminate 54 years later with Chandrayaan-3 landing near the Moon's south pole in 2023.",
    (7, 21): "On July 21, 1858, the British Crown formally absorbed the East India Company's territories — a massive administrative transfer that made India the 'jewel in the crown' of the British Empire.",
    (7, 22): "On July 22, 1947, the Indian Constituent Assembly adopted the national flag — Ashoka's wheel replacing Gandhi's spinning charkha at the insistence of secular nationalists.",
    (7, 23): "On July 23, 1856, Bal Gangadhar Tilak was born in Ratnagiri; he popularised public Ganesh festivals, launched the Swadeshi movement, and coined the phrase 'Swaraj is my birthright.'",
    (7, 24): "On July 24, 1870, the first post office in Bombay was established — part of India's postal network that at its peak became the world's largest, serving even the most remote Himalayan villages.",
    (7, 25): "On July 25, 1990, India launched INS Chakra — a nuclear-powered submarine leased from Russia — beginning its journey toward a credible nuclear triad.",
    (7, 26): "On July 26, 1999, India officially declared victory in the Kargil War — a conflict fought at altitudes above 5,000 metres in some of the most extreme battle conditions in military history.",
    (7, 27): "On July 27, 1953, the Korean War ended; thousands of Indian soldiers served in the UN Korean War Commission's medical units, showcasing India's commitment to international peacekeeping.",
    (7, 28): "On July 28, 1914, World War I began in Europe; it reshaped India by mobilising 1.5 million Indian soldiers who fought from France to Mesopotamia, fuelling demands for Indian self-rule.",
    (7, 29): "On July 29, 1880, the Vernacular Press Act was repealed after intense protest — an early victory for Indian civil society in the battle for press freedom and the right to criticise colonial rule.",
    (7, 30): "On July 30, 1968, the Nuclear Non-Proliferation Treaty opened for signatures; India refused to sign, arguing the treaty was discriminatory — a position that defined India's nuclear posture for decades.",
    (7, 31): "On July 31, 1880, India's famous blue-tinted 'Indigo revolt' concluded with Bengali farmers winning key concessions — a campaign of civil disobedience that Gandhi later studied for its techniques.",

    # ── August ────────────────────────────────────────────────────────────────
    (8,  1): "On August 1, 1920, Gandhi launched the Non-Cooperation Movement — the first mass campaign against British rule — urging Indians to boycott courts, schools, and British goods.",
    (8,  2): "On August 2, 1858, the Government of India Act was passed, transferring power from the East India Company to the British Crown — the official beginning of the 'British Raj.'",
    (8,  3): "On August 3, 1492, Columbus set sail westward searching for India — and reached the Americas instead, beginning a global re-drawing of geography rooted in the search for Indian spices.",
    (8,  4): "On August 4, 1944, Anne Frank's family was discovered in their Amsterdam hiding place; across the world, Indian soldiers of the British Indian Army were fighting in Italy and Burma.",
    (8,  5): "On August 5, 2020, PM Modi laid the foundation stone for the Ram Mandir in Ayodhya, marking the beginning of construction at one of Hinduism's holiest sites after 500 years of dispute.",
    (8,  6): "On August 6, 1945, the atomic bomb fell on Hiroshima; India's own nuclear journey would take a different path, pursuing peaceful uses through the Atomic Energy Act of 1948.",
    (8,  7): "On August 7, 1942, Gandhi proposed the 'Quit India' resolution at the Bombay session of the All-India Congress Committee — one of the most defining moments of India's freedom struggle.",
    (8,  8): "On August 8, 1942, the Quit India Movement began; within hours, Gandhi and all Congress leaders were arrested — the British thought this would crush the movement, but it only intensified it.",
    (8,  9): "On August 9, 1945, the second atomic bomb fell on Nagasaki; that same day in India, Gandhi's arrest triggered the largest uprising against British rule in the country's colonial history.",
    (8, 10): "On August 10, 1947, five days before independence, the boundary between India and Pakistan was officially finalised — a line drawn in 36 days that displaced 15 million people.",
    (8, 11): "On August 11, 1947, Pakistan's founder Muhammad Ali Jinnah delivered his famous secularism speech in Karachi, promising equal rights to all citizens regardless of religion.",
    (8, 12): "On August 12, 1765, the Mughal Emperor Shah Alam II granted the British East India Company the 'Diwani' rights over Bengal, Bihar, and Odisha — effectively making it the ruler of eastern India.",
    (8, 13): "On August 13, 1947, the last day before independence, millions of Indians waited through the night for midnight — Nehru's 'Tryst with Destiny' address was being prepared in New Delhi.",
    (8, 14): "On August 14, 1947, Pakistan was born at midnight — the world's first modern nation created specifically for a religious majority, and India's closest and most complex neighbour.",
    (8, 15): "On August 15, 1947, India declared independence from British rule at midnight, with Jawaharlal Nehru's immortal words — 'Long years ago we made a tryst with destiny' — ringing over All India Radio.",
    (8, 16): "On August 16, 1946, Jinnah called for 'Direct Action Day' — the resulting Calcutta killings claimed thousands of lives and made Partition seem unavoidable to both sides.",
    (8, 17): "On August 17, 1947, the Radcliffe Line was made public — millions of Indians and Pakistanis discovered for the first time which side of the new border their homes fell on.",
    (8, 18): "On August 18, 1947, Indian troops entered Kashmir for the first time as Maharaja Hari Singh signed the Instrument of Accession — the event that began a conflict still unresolved today.",
    (8, 19): "On August 19, 1949, India signed its first trade agreement with China — a gesture of goodwill that preceded the famous 'Hindi-Chini Bhai Bhai' era before the 1962 border war.",
    (8, 20): "On August 20, 1944, India's first nuclear physicist Homi Bhabha wrote to Nehru proposing India's atomic programme — one of the most consequential letters in modern Indian science history.",
    (8, 21): "On August 21, 1888, ISRO's spiritual predecessor — the Indian Meteorological Department — was formally established; Indian observation of the sky predates this by thousands of years.",
    (8, 22): "On August 22, 1851, the Great Trigonometrical Survey completed its measurement of India — a colossal mapping project that confirmed the Himalayas as the world's tallest mountain range.",
    (8, 23): "On August 23, 2023, India's Chandrayaan-3 successfully landed near the Moon's south pole — making India the first nation to achieve this feat and only the fourth to land on the Moon.",
    (8, 24): "On August 24, 1608, English explorer Henry Hudson reached the Arctic in his search for a northeast passage to Asia — at the same time, the Mughal Empire was India's most powerful kingdom.",
    (8, 25): "On August 25, 1947, the first refugees of Partition crossed the Punjab border — the beginning of the largest mass migration in human history, with 15 million people displaced in weeks.",
    (8, 26): "On August 26, 1910, Mother Teresa was born in Skopje; she would spend most of her life in Calcutta, founding the Missionaries of Charity and winning the Nobel Peace Prize in 1979.",
    (8, 27): "On August 27, 1883, the Krakatoa volcano erupted — the sound was heard in Bangalore; the ash cloud cooled global temperatures and failed harvests worsened India's devastating 1884 famine.",
    (8, 28): "On August 28, 1963, Martin Luther King Jr. delivered his 'I Have a Dream' speech — directly drawing on Mahatma Gandhi's philosophy of non-violent resistance for racial equality.",
    (8, 29): "On August 29, 1905, the Partition of Bengal was formally announced by Viceroy Curzon — triggering the Swadeshi movement, the most significant economic nationalism campaign before 1942.",
    (8, 30): "On August 30, 1947, Jawaharlal Nehru's first cabinet was sworn in, including Ambedkar as Law Minister, Sardar Patel as Home Minister, and Maulana Azad as Education Minister.",
    (8, 31): "On August 31, 1920, the Khilafat Movement's central committee met in Calcutta to plan non-cooperation with the British — a rare moment of Hindu-Muslim unity that Gandhi helped organise.",

    # ── September ─────────────────────────────────────────────────────────────
    (9,  1): "On September 1, 1939, World War II began — India was declared a belligerent without consulting its own leaders, an act of imperial arrogance that supercharged the independence movement.",
    (9,  2): "On September 2, 1945, Japan surrendered and World War II ended — 2.5 million Indian soldiers had served in the conflict, and Britain's promise of independence was now unavoidable.",
    (9,  3): "On September 3, 1948, Hyderabad's Nizam surrendered to Indian forces after a 5-day 'police action' — Operation Polo — integrating the last major holdout princely state into India.",
    (9,  4): "On September 4, 1951, the first general elections in independent India were announced — a single-phase election of astonishing scale involving 176 million first-time voters.",
    (9,  5): "On September 5, Teachers' Day in India, the birth anniversary of Dr. S. Radhakrishnan — philosopher, president, and one of India's greatest intellects — is celebrated nationwide.",
    (9,  6): "On September 6, 1965, Pakistani forces crossed the international border into Punjab — India responded with counter-attacks toward Lahore in what became the 1965 Indo-Pakistani War.",
    (9,  7): "On September 7, 1947, a British military convoy was ambushed near Peshawar — a reminder that even as Britain withdrew from India, the new nations were already in violent conflict.",
    (9,  8): "On September 8, 1900, the Indian Plague Commission confirmed that the bubonic plague killed over 1 million people in India over the preceding five years — a calamity that fuelled nationalist anger.",
    (9,  9): "On September 9, 1947, Sardar Vallabhbhai Patel declared that the 565 princely states had all agreed to accede to India — one of the greatest diplomatic achievements in the nation's history.",
    (9, 10): "On September 10, 1897, Bal Gangadhar Tilak was sentenced to 18 months of rigorous imprisonment for writing articles deemed seditious — his defiant speech in court became legendary.",
    (9, 11): "On September 11, 1893, Swami Vivekananda addressed the Parliament of World's Religions in Chicago, famously beginning 'Sisters and Brothers of America' — electrifying the audience with Indian philosophy.",
    (9, 12): "On September 12, 1948, Hyderabad's Nizam formally signed the Instrument of Accession — completing Sardar Patel's 18-month project of unifying India's fractured princely landscape.",
    (9, 13): "On September 13, 1948, Indian troops entered Hyderabad State — within five days, the Nizam's forces surrendered and the last major barrier to India's territorial integrity was removed.",
    (9, 14): "On September 14, 1949, the Constituent Assembly adopted Hindi in the Devanagari script as India's official language — a controversial decision that sparked protests in Tamil Nadu and other states.",
    (9, 15): "On September 15, 1948, Homi Bhabha was appointed chairman of India's Atomic Energy Commission — the beginning of the nuclear programme that would culminate in the 1974 Pokhran test.",
    (9, 16): "On September 16, 1932, Gandhi began a 'fast unto death' in Poona Jail to protest the separate electorate for Dalits — his fast forced the Poona Pact, which shaped Dalit political representation.",
    (9, 17): "On September 17, 1948, Operation Polo concluded as the Nizam of Hyderabad signed the Instrument of Accession, bringing one of the world's wealthiest states into democratic India.",
    (9, 18): "On September 18, 1982, India hosted the Asian Games in Delhi for the second time — an event that modernised the capital's infrastructure and announced India as a sporting and diplomatic power.",
    (9, 19): "On September 19, 1893, Vivekananda addressed the Chicago Parliament of Religions for the last time — his words helped establish the Vedanta Society and sparked lasting Western interest in Indian philosophy.",
    (9, 20): "On September 20, 1857, British forces recaptured Delhi from the rebels of the Indian Revolt, effectively ending the main phase of the uprising and sealing the fate of the last Mughal emperor.",
    (9, 21): "On September 21, 1932, the Poona Pact was signed between Gandhi and Ambedkar — ensuring reserved constituencies for Dalits and marking a pivotal moment in India's caste and democracy politics.",
    (9, 22): "On September 22, 1965, the UN brokered a ceasefire in the Indo-Pakistani War — 22 days of fighting ended with neither side gaining significant ground but India repelling the Pakistani advance.",
    (9, 23): "On September 23, 1923, the Rashtriya Swayamsevak Sangh (RSS) was founded by K.B. Hedgewar in Nagpur — an organisation whose ideology continues to shape Indian politics nearly a century later.",
    (9, 24): "On September 24, 2014, India's Mars Orbiter Mission (Mangalyaan) successfully entered Mars orbit — making India the first nation to succeed on its maiden Mars attempt and the fourth to reach Mars.",
    (9, 25): "On September 25, 1932, Pt. Deen Dayal Upadhyaya was born — the political thinker whose philosophy of 'Integral Humanism' became the ideological foundation of the Bharatiya Janata Party.",
    (9, 26): "On September 26, 1687, the Mughal Emperor Aurangzeb captured Bijapur — the final defeat of the Deccan Sultanates, temporarily extending Mughal control over the entire Indian subcontinent.",
    (9, 27): "On September 27, 1825, the world's first steam-powered railway opened in Stockton, England — just 28 years before India would open its own first railway between Bombay and Thane.",
    (9, 28): "On September 28, 1907, Bhagat Singh was born in Lyallpur (now Faisalabad, Pakistan) — the revolutionary whose courage and sacrifice made him an eternal icon of India's freedom struggle.",
    (9, 29): "On September 29, 1907, the Indian National Congress session at Surat saw the famous 'split' between moderates and extremists — a fracture in Indian nationalism that reshaped independence politics.",
    (9, 30): "On September 30, 1954, the French enclave of Chandannagar was formally merged into West Bengal — the beginning of France's withdrawal from its Indian territories, completed with Pondicherry in 1962.",

    # ── October ───────────────────────────────────────────────────────────────
    (10,  1): "On October 1, 1953, Andhra State was created as the first state carved out on a linguistic basis in India — a landmark that triggered the broader States Reorganisation movement.",
    (10,  2): "On October 2, 1869, Mahatma Gandhi was born in Porbandar, Gujarat — the man who transformed non-violence from a personal virtue into a political weapon that changed world history.",
    (10,  3): "On October 3, 1992, India launched INSAT-2A — its first fully operational indigenous satellite — from French Guiana, advancing the space programme Vikram Sarabhai had dreamed of.",
    (10,  4): "On October 4, 1957, the Soviet Union launched Sputnik — the first artificial satellite; India's space programme, launched years later, would eventually deploy more than 400 satellites in orbit.",
    (10,  5): "On October 5, 1962, China launched a surprise attack on India's northern border, beginning the Sino-Indian War — a defeat that reshaped India's foreign and defence policy for decades.",
    (10,  6): "On October 6, 1989, the Dalai Lama was awarded the Nobel Peace Prize — the Tibetan spiritual leader has lived in exile in Dharamsala, India, since 1959 after fleeing Chinese occupation.",
    (10,  7): "On October 7, 1959, China published a map claiming large areas of Indian territory in Ladakh and Arunachal Pradesh — the beginning of a border dispute that remains unresolved today.",
    (10,  8): "On October 8, 1932, the Indian Air Force was officially established — today one of the world's largest air forces, with origins as a small colonial auxiliary squadron.",
    (10,  9): "On October 9, 1934, India's first telegraph line was laid between Calcutta and Diamond Harbour — the beginning of a communications revolution that would transform the subcontinent.",
    (10, 10): "On October 10, 1943, Subhas Chandra Bose proclaimed the Provisional Government of Free India in Singapore, backed by Japan and commanding the Indian National Army.",
    (10, 11): "On October 11, 1902, Jai Prakash Narayan was born — the Gandhian socialist who launched the 'Total Revolution' against Indira Gandhi's Emergency in 1974 and restored Indian democracy.",
    (10, 12): "On October 12, 1492, Columbus arrived in the Americas — having sailed westward to find India; the Caribbean islands he misnamed 'the Indies' reflect just how powerful India's allure was.",
    (10, 13): "On October 13, 1948, India's Jawaharlal Nehru made his first major speech at the United Nations — presenting a non-aligned foreign policy vision that would define India's global role.",
    (10, 14): "On October 14, 1956, B.R. Ambedkar converted to Buddhism in a mass ceremony in Nagpur along with 600,000 followers — one of the largest religious conversions in modern history.",
    (10, 15): "On October 15, 1931, A.P.J. Abdul Kalam was born in Rameswaram, Tamil Nadu — the 'Missile Man of India' who led the ISRO and DRDO programmes before becoming the 11th President of India.",
    (10, 16): "On October 16, 1905, the Partition of Bengal came into effect — Lord Curzon's administrative division ignited the Swadeshi movement, the most powerful anti-colonial economic protest India had seen.",
    (10, 17): "On October 17, 1948, the Indian Constitution's draft was presented to the Constituent Assembly by Dr. Ambedkar — a document that took 2 years, 11 months, and 18 days to complete.",
    (10, 18): "On October 18, 1998, cyclone Zelie devastated parts of the Bay of Bengal coast; Kerala's southwestern coast remains one of India's most storm-vulnerable coastal zones.",
    (10, 19): "On October 19, 1962, China launched a second wave of attacks across the Himalayas — Indian forces, ill-equipped for high-altitude warfare, were pushed back in a humiliating military defeat.",
    (10, 20): "On October 20, 1962, China launched its surprise attack across the McMahon Line into NEFA (now Arunachal Pradesh) — India's biggest military crisis since independence.",
    (10, 21): "On October 21, 1943, Subhas Chandra Bose declared the Azad Hind Government in Singapore — a government-in-exile that commanded 45,000 soldiers of the Indian National Army.",
    (10, 22): "On October 22, 2008, India launched Chandrayaan-1 — its first lunar mission, which discovered water molecules on the Moon's surface, transforming human understanding of Earth's satellite.",
    (10, 23): "On October 23, 1951, India's first general election voting began in Himachal Pradesh — 40 years after women's suffrage was won in Norway, India gave ALL its citizens the vote from day one.",
    (10, 24): "On October 24, 1945, the United Nations was founded; India was one of the original 50 signatories, though it was still under British rule — an anomaly that ended two years later.",
    (10, 25): "On October 25, 1947, Maharaja Hari Singh signed the Instrument of Accession for Jammu & Kashmir to India — triggering the first Indo-Pakistani War and a dispute that endures to this day.",
    (10, 26): "On October 26, 1947, Indian troops were airlifted into Srinagar airport — the first military airlift in India's history, successfully repelling Pakistani-backed tribal fighters from the valley.",
    (10, 27): "On October 27, 1947, UN Security Council Resolution 39 was passed, calling for a ceasefire in Kashmir — but the fighting continued for another 15 months before peace was restored.",
    (10, 28): "On October 28, 1962, China declared a unilateral ceasefire in the Sino-Indian War — withdrawing to the position it held before the war, but keeping territories it had seized.",
    (10, 29): "On October 29, 1945, Subhas Chandra Bose's INA soldiers were tried for treason in Delhi's Red Fort — their defence by Nehru and Jinnah turned the trials into a nationalist cause célèbre.",
    (10, 30): "On October 30, 1909, the Minto-Morley Reforms were announced, giving Indians limited participation in governance — a small concession that nationalist leaders criticised as grossly inadequate.",
    (10, 31): "On October 31, 1984, Prime Minister Indira Gandhi was assassinated by her Sikh bodyguards — a killing followed by anti-Sikh riots that killed over 3,000 people across India.",

    # ── November ──────────────────────────────────────────────────────────────
    (11,  1): "On November 1, 1956, Kerala was officially formed under the States Reorganisation Act, uniting Malayalam-speaking regions of Travancore-Cochin and Malabar into India's most literate state.",
    (11,  2): "On November 2, 1945, the INA trials ended with the British wisely abandoning prosecutions — the three accused (Hindu, Muslim, and Sikh) had become national heroes, not criminals.",
    (11,  3): "On November 3, 1957, the Soviet Union launched Sputnik 2 carrying the dog Laika — India's own space agency ISRO was just a few years away from launching its first sounding rockets.",
    (11,  4): "On November 4, 1948, India joined the United Nations — its first act of international diplomacy as a fully sovereign nation, advocating for decolonisation and non-alignment globally.",
    (11,  5): "On November 5, 1556, the Second Battle of Panipat was fought — Akbar's forces defeated Hemu under the regency of Bairam Khan, consolidating Mughal rule over northern India.",
    (11,  6): "On November 6, 1945, the British Parliament debated Indian independence for the first time — the post-war exhaustion made sustaining an empire increasingly impossible.",
    (11,  7): "On November 7, 1888, Chandrashekhar Azad was born in Bhavra; the revolutionary who vowed never to be captured alive died by his own hand in Allahabad's Alfred Park, keeping his promise.",
    (11,  8): "On November 8, 2016, India announced the demonetisation of ₹500 and ₹1,000 notes — affecting 86% of the country's cash supply in one of the most audacious economic moves in Indian history.",
    (11,  9): "On November 9, 2019, the Supreme Court ruled in favour of the Ram Temple in Ayodhya — ending a legal dispute that had lasted over a century and reshaping India's religio-political landscape.",
    (11, 10): "On November 10, 1917, India's first ICS (Indian Civil Service) examination was held in London — a system that later evolved into the IAS and still governs India's vast administrative machinery.",
    (11, 11): "On November 11, 1918, World War I ended — 74,000 Indian soldiers had died in the conflict, yet Britain still refused to grant India self-rule, igniting a new wave of nationalist anger.",
    (11, 12): "On November 12, 1781, the Battle of Pollilur was fought — Hyder Ali's forces defeated the British under Colonel Baillie in the most devastating British loss in the Anglo-Mysore Wars.",
    (11, 13): "On November 13, 1879, the Vernacular Press Act was passed by Lord Lytton, restricting Indian-language newspapers — a censorship that backfired by transforming Indian journalism into a resistance movement.",
    (11, 14): "On November 14, 1889, Jawaharlal Nehru was born in Allahabad; India celebrates Children's Day on this date to honour the leader whose affection for children was legendary.",
    (11, 15): "On November 15, 2000, Jharkhand was carved out of Bihar — bringing statehood to India's tribal heartland and ending decades of demands for recognition of the Adivasi communities.",
    (11, 16): "On November 16, 1945, the United Nations Educational, Scientific and Cultural Organization (UNESCO) was founded; India was a founding member and has designated 42 UNESCO World Heritage Sites.",
    (11, 17): "On November 17, 1869, the Suez Canal officially opened — cutting the sea journey from Britain to India from 24,000 km to 11,000 km and transforming the economics of the empire.",
    (11, 18): "On November 18, 1477, William Caxton printed the first book in England; India had been printing texts in Sanskrit and regional scripts for centuries, with some of Asia's oldest printing traditions.",
    (11, 19): "On November 19, 1917, Indira Gandhi was born in Allahabad — she would become India's first female Prime Minister, serving three full terms and reshaping Indian politics from 1966 to 1984.",
    (11, 20): "On November 20, 1945, the Nuremberg Trials began; India's own justice for Partition-era violence was sought through commissions that documented but rarely prosecuted the crimes of 1947.",
    (11, 21): "On November 21, 1963, Delhi University's history department held its first seminar on the Indian National Movement — historians began reclaiming the narrative of India's freedom struggle.",
    (11, 22): "On November 22, 1963, US President JFK was assassinated; two months later, India's Lal Bahadur Shastri would take office as PM following Nehru's death, in a very different kind of transition.",
    (11, 23): "On November 23, 1947, the Indian army launched a major offensive in Kashmir, pushing Pakistani-backed fighters back from the outskirts of Srinagar and securing the valley.",
    (11, 24): "On November 24, 1963, Jack Ruby shot Lee Harvey Oswald on live television in Dallas; Indian papers covered it on the front page, reflecting how closely India followed American politics.",
    (11, 25): "On November 25, 1949, the Indian Constituent Assembly adopted the Constitution — Dr. Ambedkar declared it 'a Constitution for all citizens,' closing three years of remarkable democratic deliberation.",
    (11, 26): "On November 26, 1949, India's Constitution was adopted by the Constituent Assembly — now celebrated as Constitution Day, honouring the document that guarantees rights to 1.4 billion people.",
    (11, 27): "On November 27, 1947, Lord Mountbatten visited Lahore to negotiate a Kashmir ceasefire — just 3 months after Partition, the two nations were already in armed conflict over a shared princely state.",
    (11, 28): "On November 28, 1520, Magellan's fleet entered the Pacific Ocean — the same decade that Babur was consolidating the Mughal dynasty in India, beginning 300 years of Muslim imperial rule.",
    (11, 29): "On November 29, 1947, the UN General Assembly voted for the Partition of Palestine — a decision that resonated in India, itself just three months past its own partition into India and Pakistan.",
    (11, 30): "On November 30, 1947, India's first Prime Minister Nehru addressed the nation on All India Radio urging calm after Partition violence — his voice was one of the few stabilising forces in the chaos.",

    # ── December ──────────────────────────────────────────────────────────────
    (12,  1): "On December 1, 1955, Rosa Parks refused to give up her bus seat in Montgomery, Alabama; Gandhi's non-violent civil disobedience, which had inspired King, now sparked the American civil rights movement.",
    (12,  2): "On December 2, 1984, the Bhopal gas tragedy began as methyl isocyanate gas leaked from the Union Carbide plant — killing over 3,700 people immediately and affecting half a million, India's worst industrial disaster.",
    (12,  3): "On December 3, 1971, Pakistan launched pre-emptive air strikes on Indian airbases, formally beginning the 1971 Indo-Pakistani War — a conflict India decisively won in 13 days.",
    (12,  4): "On December 4, 1971, the Indian Navy struck Karachi harbour in Operation Trident — the most successful naval action in South Asian history, destroying Pakistani fuel depots and ships.",
    (12,  5): "On December 5, 1950, Sardar Vallabhbhai Patel — the 'Iron Man of India' who integrated 565 princely states into the union — died in Bombay, leaving behind a consolidated nation.",
    (12,  6): "On December 6, 1992, the Babri Masjid in Ayodhya was demolished by a mob — triggering communal violence across India and a legal and political dispute resolved only in 2019.",
    (12,  7): "On December 7, 1988, Benazir Bhutto was sworn in as Pakistan's Prime Minister — the first woman to lead a Muslim-majority nation and a neighbour India had fought three wars with.",
    (12,  8): "On December 8, 1971, India recognised Bangladesh as an independent nation — just five days before Pakistani forces surrendered in the most decisive military victory in Indian history.",
    (12,  9): "On December 9, 1946, the Indian Constituent Assembly held its first meeting in Constitution Hall, New Delhi — beginning a 2-year, 11-month project to write the world's longest constitution.",
    (12, 10): "On December 10, 1950, Mother Teresa founded the Missionaries of Charity in Calcutta — an organisation dedicated to serving India's poorest of the poor, now active in 139 countries.",
    (12, 11): "On December 11, 1946, the Constituent Assembly appointed Dr. B.R. Ambedkar to chair the drafting committee — the man best qualified by scholarship and personal experience to write India's Constitution.",
    (12, 12): "On December 12, 1911, King George V's Durbar was held in Delhi, and the capital of India was officially moved from Calcutta to Delhi — a decision that gave New Delhi its place in history.",
    (12, 13): "On December 13, 2001, terrorists attacked India's Parliament building in New Delhi — the assault on democracy's temple brought India and Pakistan to the brink of their fourth war.",
    (12, 14): "On December 14, 1911, the South Pole was first reached by Roald Amundsen — the same month India's capital was moved to Delhi at the Delhi Durbar, both events reshaping human geography.",
    (12, 15): "On December 15, 1971, General Niazi of Pakistan signed the Instrument of Surrender in Dhaka — 93,000 Pakistani soldiers laid down arms in the largest military surrender since World War II.",
    (12, 16): "On December 16, 1971, Bangladesh was liberated when Pakistani forces surrendered — a war India fought and won in 13 days, creating a new nation and 10 million refugees came home.",
    (12, 17): "On December 17, 1927, the All-India Radio was inaugurated in Delhi and Calcutta — the national broadcaster that would become the primary means of communication during independence, partition, and war.",
    (12, 18): "On December 18, 1961, India conducted Operation Vijay and liberated Goa from 451 years of Portuguese colonial rule — the last colony on the Indian subcontinent was finally free.",
    (12, 19): "On December 19, 1961, India formally integrated Goa, Daman, and Diu into the Indian Union — giving the subcontinent its complete territorial unification for the first time since independence.",
    (12, 20): "On December 20, 1503, Leonardo da Vinci completed the Mona Lisa — painting it in the same decades that Babur and the early Mughals were bringing a Persian renaissance to Indian court culture.",
    (12, 21): "On December 21, 1988, India signed the South Asian Association for Regional Cooperation charter — the creation of SAARC linking India with its seven neighbours remains central to regional diplomacy.",
    (12, 22): "On December 22, 1666, the birth anniversary of Emperor Aurangzeb — whose policies of religious intolerance reversed the pluralism of Akbar's reign and weakened the Mughal Empire from within.",
    (12, 23): "On December 23, 1988, the Palk Strait tunnel project was proposed to link India and Sri Lanka — a 28 km undersea connection that engineers and diplomats still debate today.",
    (12, 24): "On December 24, 1977, Morarji Desai was sworn in as India's first non-Congress Prime Minister — a watershed moment proving India's democracy could peacefully change governments after 30 years of one-party rule.",
    (12, 25): "On December 25, 1861, the Viceroy Lord Canning issued the infamous 'Canning Circular' restricting the press; Christmas Day in India is a public holiday celebrated across communities regardless of faith.",
    (12, 26): "On December 26, 2004, the Indian Ocean tsunami struck the Andaman and Nicobar Islands, Kerala's coast, and Tamil Nadu — killing over 10,000 Indians and 230,000 people across 14 countries.",
    (12, 27): "On December 27, 1945, the International Monetary Fund was established — India was a founding member and has maintained a complex relationship with IMF structural adjustment ever since.",
    (12, 28): "On December 28, 1885, the Indian National Congress was founded in Bombay by A.O. Hume — a political party that would lead India to independence and govern it for most of its first 60 years.",
    (12, 29): "On December 29, 1940, the Muslim League formally committed to the Lahore Resolution's demand for Pakistan — setting in motion events that would divide the subcontinent within seven years.",
    (12, 30): "On December 30, 1943, Subhas Chandra Bose raised the Indian flag in Port Blair, Andaman Islands — the first Indian territory to be 'liberated' by the Azad Hind government.",
    (12, 31): "On December 31, 1600, Queen Elizabeth I signed the charter of the British East India Company — setting in motion a trade enterprise that would grow into an empire spanning an entire subcontinent.",
}

_DEFAULT = "India's rich tapestry of history, culture, and geography makes every day a great day to test your knowledge — jump in and play Sigmionary!"


def get_history_fact(month: int, day: int) -> str:
    """Return the history fact for the given calendar day, or a default if not found."""
    return _FACTS.get((month, day), _DEFAULT)
